name = "DownloadDirectories"
uuid = "7ccd7fa4-5880-4e7b-b140-9236e3e96f31"
version = "0.1.0"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
Downloads = "1.7.0"
URIs = "1.6.1"
